entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: infra-backend

certificatesResolvers:
  letsencrypt:
    acme:
      email: "actionboard.admin@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

accessLog: {}

log:
  level: INFO

metrics:
  prometheus: {}
